User.create!(name: "Admin", email: "admin@srmmyhelp.com", password: "12345", password_confirmation: "12345", roles: "Admin", csrg: nil)

User.create!(name: "General Motors", email: "gm@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Kohls Corp", email: "kc@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Nbc Sports", email: "ns@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Rockwell", email: "rcw@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Flipkart", email: "fkt@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Dell Usa Lp", email: "dul@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Bajaj Finance", email: "bjf@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG2')
User.create!(name: "Avaya Inc", email: "ai@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG2')
User.create!(name: "HCL Technologies", email: "ht@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG2')
User.create!(name: "Nikon", email: "nikon@example.com", password: "12345", password_confirmation: "12345", roles: "Customer", csrg: 'CSG2')

User.create!(name: "Mukesh Singh Rathaur", email: "mukesh.rathaur@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Ghanshyam Rathod", email: "ghanshyam.rathod@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG2')
User.create!(name: "Abhinav Gupta", email: "abhinav.gupta@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG12')
User.create!(name: "Chandra Jangam", email: "chandra.jangam@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Chandra Mouli", email: "chandramouli.gollapalli@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Durgesh Tripathi", email: "durgesh.tripathi@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG2')
User.create!(name: "Arivarsan C", email: "arivarasan.chandrasekaran@oracle.com", password: "12345", password_confirmation: "12345", roles: "CSR", csrg: 'CSG3')
