User.create!(name: "Admin", email: "admin@srmmyhelp.com", password: "12345", password_confirmation: "12345", roles: "Admin", csrg: nil)
User.create!(name: "Mukesh Singh Rathaur", email: "mukesh.rathaur@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Ghanshyam Rathod", email: "ghanshyam.rathod@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG2')
User.create!(name: "Abhinav Gupta", email: "abhinav.gupta@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG12')
User.create!(name: "Chandra Jangam", email: "chandra.jangam@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Chandra Mouli", email: "chandramouli.gollapalli@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG1')
User.create!(name: "Durgesh Tripathi", email: "durgesh.tripathi@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG2')
User.create!(name: "Arivarsan C", email: "arivarasan.chandrasekaran@oracle.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "CSR", csrg: 'CSG3')

User.create!(name: "Customer One", email: "customer1@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Two", email: "customer2@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Three", email: "customer3@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Four", email: "customer4@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Five", email: "customer5@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Six", email: "customer6@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG1')
User.create!(name: "Customer Seven", email: "customer7@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG2')
User.create!(name: "Customer Eight", email: "customer8@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG2')
User.create!(name: "Customer Nine", email: "customer9@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG2')
User.create!(name: "Customer Ten", email: "customer10@example.com", password: "Srm_Ora", password_confirmation: "Srm_Ora", roles: "Customer", csrg: 'CSG2')